# Generated by Django 5.0.6 on 2024-06-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_propuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='propuesta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
            preserve_default=False,
        ),
    ]
