# Generated by Django 5.0.6 on 2024-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_delete_usuario_alter_propuesta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='fecha_creacion',
        ),
    ]
