# Generated by Django 5.0.6 on 2024-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_propuesta_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
